vehicles_data= [
    {"name": "Terberg FM 2850 hiab 200c + 10x4 + fully functional  + euro 5+" , "subcategory":"crane_truck","price":43950},
    {"name": "Terberg FM 1450 WITTIG VACUM SYSTEM + TIPPER + FULLY WORKING + EURO 2 + ADR + 11+" , "subcategory":"34m3vacuum_truck","price":37950},
    {"name": "Terberg FM 380 MANUAL - BIG AXLE - BELGIUM TOP TRUCK+" , "subcategory":"container_truck","price":12500},
    {"name": "Terberg FM 2850 10X4 EURO 3 / HOLLAND TRUCK !!!+" , "subcategory":"drop_side_truck","price":9500},
    {"name": "Terberg FM 1350 -WDGL 6x6 met 2 zijden kipper en HMF 1643 Z 2 kraan+" , "subcategory":"tipper_truck","price":38900},
    {"name": "Terberg FM 1950-HT+" , "subcategory":"container_truck","price":0},
    {"name": "Terberg YT 222 Trekker+" , "subcategory":"swap_body_truck","price":0},
    {"name": "Terberg CC YT 182 4x2 CC","subcategory":"container_truck","price":0},
    {"name": "Terberg FM 2850 400 10x4 Euro 5 Mulder 15 Kub Mixer NL Truck!+" , "subcategory":"concrete_mixer_truck","price":36000},
    {"name": "Terberg FM 1350 6x6 Euro 5 met demontable 17 Tonmeter laadkraan+" , "subcategory":"container_truck","price":37500},
    {"name": "Terberg BC 182 Umsetzer, Wiesel, Kamag+" , "subcategory":"swap_body_truck","price":33800},
    {"name": "Terberg YT 180+" , "subcategory":"container_truck","price":1},
    {"name": "Terberg FM 2850 420 10x4 EEV Euro 5 Liebherr 15 Kub Mixer!+" , "subcategory":"concrete_mixer_truck","price":0},
    {"name": "Terberg FM 1850 -T 8X4 NL-Truck 30tons cable system Lift+Lenkachse Euro 5+" ,"subcategory":"container_truck","price":22500},
    {"name": "Terberg F 2850-WG1 10x4 handgeschakeld met 15m3 Mulder mixer+" , "subcategory":"concrete_mixer_truck","price":12900},
    {"name": "Terberg BC 182 Umsetzer Sattelkupplung WBH25 Rangier Kam+" , "subcategory":"swap_body_truck","price":38900},
    {"name": "Terberg FM 1350 6X6 EURO 5 / Z KRAN + 2 SIDE TIPPER+" , "subcategory":"tipper_truck","price":37900},
    {"name": "Terberg FM 2850 Terberg  10x4  handgeschakeld+" , "subcategory":"chassis_cab_truck","price":10250},
    {"name": "Terberg 1450-WDGL ADR+" , "subcategory":"chassis_cab_truck","price":15000},
    {"name": "Terberg FM 2850 420 EEV 10x4 Euro 5 Liebherr 15 Kub Mixer NL Truck!+" , "subcategory":"concrete_mixer_truck","price":0},
    {"name": "Terberg VOLVO FM 2850-T 10X4 tipper+" , "subcategory":"tipper_truck","price":17900},
    {"name": "Terberg FM 2850 EURO 5 10x4 kettingsysteem+" , "subcategory":"container_truck","price":39500},
    {"name": "Terberg FL1350-WDG - 6x6+" , "subcategory":"container_truck","price":0},
    {"name": "Terberg BC 182 Sattelkupplung AHK Umsetzfahrzeug KLIMA W+" , "subcategory":"swap_body_truck","price":36900},
    {"name": "Terberg BC 182 Sattelkupplung 2xAHK Umsetzfahrzeug KLIMA+" ,"subcategory":"swap_body_truck","price":33900},
    {"name": "Terberg FM 3000 10x8+" , "subcategory":"tipper_truck","price":0},
    {"name": "Terberg FM 3000+" , "subcategory":"tipper_truck","price":24900},
    {"name": "Terberg FM1450-WDGL 6x4+" , "subcategory":"container_truck","price":0},
    {"name": "Terberg FL1350-WDG1 6x6 Tipper+" , "subcategory":"tipper_truck","price":0},
    {"name": "Terberg F1150S 4x4+" , "subcategory":"truck_mounted_boom_lift","price":0},
    {"name": "Terberg FM2850 - 8x4 - Chassis truck+" , "subcategory":"chassis_cab_truck","price":0},
    {"name": "Terberg FM2850 - 10x4+" , "subcategory":"container_truck","price":0}
]

